version: 2
update_configs:
  - package_manager: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "in_range"
